### ISSUE TITLE
Translation error from imgui_impl_sdl2.h to  cimgui_impl_sdl2.h 

### ISSUE THREAD

**Issue by dinau** [dearimgui/dear_bindings#71]
- Dear Bindings latest version   
- ImGui verison: 1.90.7 and 1.90.8 WIP at least
- Windows10 OS
- Python 3.12.3

It seems to fail parsing `ImGui_ImplSDL2_SetGamepadMode()` function,  
"**Unrecognised element LexToken(LPAREN,'(',43,2796)**" ?

```sh
python ../../libs/dear_bindings/dear_bindings.py --backend --imconfig-path ../../libs/imgui/imconfig.h -o cimgui/cimgui_impl_sdl2 ../../libs/imgui/backends/imgui_impl_sdl2.h
Dear Bindings: parse Dear ImGui headers, convert to C and output metadata.
Parsing ../../libs/imgui/imconfig.h
Parsing ...snip...\libs\imgui\backends\imgui_impl_sdl2.h
Unrecognised element LexToken(LPAREN,'(',43,2796)
Storing unmodified DOM
Applying modifiers
Writing output to cimgui/cimgui_impl_sdl2[.h/.cpp/.json]
Done
```

**cimgui_impl_sdl2.h** generated is,

```c
... snip ...
IMGUI_IMPL_API
void
ImGui_ImplSDL2_SetGamepadMode
#endif // #ifndef IMGUI_DISABLE
#ifdef __cplusplus
} // End of extern "C" block
#endif
```

This is imgui/backends/**imgui_impl_sdl2.h**,

```cpp
...snip..
IMGUI_IMPL_API void     ImGui_ImplSDL2_SetGamepadMode(ImGui_ImplSDL2_GamepadMode mode, struct _SDL_GameController** manual_gamepads_array = NULL, int manual_gamepads_count = -1);

#endif // #ifndef IMGUI_DISABLE
```

So compiling source code using `cimgui_impl_sdl2.h` is failed.

**Comment by ShironekoBen** [comment]
Thanks for the report - indeed, it seems that recent version of things have broken conversion of the SDL2 backend (and wgpu, by the looks of it).

The culprit is the struct declaration inline in `ImGui_ImplSDL2_SetGamepadMode`, by the looks of it - the parser doesn't properly understand that at the moment. I'll add in support for it but in the meantime if you need a quick fix that declaration is actually redundant (there's a forward-declaration of the struct earlier in the file), so if you change that line to:
```cpp
IMGUI_IMPL_API void     ImGui_ImplSDL2_SetGamepadMode(ImGui_ImplSDL2_GamepadMode mode, _SDL_GameController** manual_gamepads_array = NULL, int manual_gamepads_count = -1);
```
...then it all seems to work.

I'll update this issue again once I've got a proper fix.

Thanks again!

**Comment by dinau** [comment]
Thank you for your detail explanation.
I will use your suggestion code.

**Comment by ShironekoBen** [comment]
Just as an update on this, I've pushed a new version which fixes both parsing issues, so the new code should work with an unmodified versions of ImGui again.

Thanks again, and just let me know if you spot anything else that's broken!
