### ISSUE TITLE
Static struct functions are emitted as instance functions

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [dearimgui/dear_bindings#73]
I don't think we even have the staticness as part of the metadata. This doesn't look like something that's super to hard to implement, but question is, should we even, or are we fine with just not emitting the static functions?

-------
Particular example: `ImColor.HSV()` is defined as:

```
static ImColor HSV(float h, float s, float v, float a = 1.0f)   { float r, g, b; ImGui::ColorConvertHSVtoRGB(h, s, v, r, g, b); return ImColor(r, g, b, a); }
```

However, it is emitted as an instance function, with a `self`` pointer and all

cimgui.h:
```
CIMGUI_API ImColor ImColor_HSV(ImColor* self, float h, float s, float v, float a /* = 1.0f */);
```

cimgui.cpp:
```
CIMGUI_API cimgui::ImColor cimgui::ImColor_HSV(cimgui::ImColor* self, float h, float s, float v, float a)
{
    return ConvertFromCPP_ImColor(reinterpret_cast<::ImColor*>(self)->ImColor::HSV(h, s, v, a));
}
```

**Comment by ShironekoBen** [comment]
Hmm... looks like I wasn't thinking very straight when I implemented that, because it strips the `static` keyword from members by actually removing the flag, which then results in the rest of the code not really knowing something was static and just treating it as a regular member function!

I've done a little bit of tweaking and fixed that so they now get emitted correctly (I think it's nicest for the user to emit them, even if there aren't very many), and also added `is_static` to the metadata.

Thanks!

**Comment by ShironekoBen** [comment]
(relevant commit is here: 97652647b8fe354b787432aae398eaa4d9945af6)
