### ISSUE TITLE
Suggestion: change "cimgui" mentions to something unique

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [dearimgui/dear_bindings#80]
Even though dear_bindings is a completely separate project from https://github.com/cimgui/cimgui, it still uses cimgui terminology - there's a `cimgui` namespace, defines like `CIMGUI_IMPL_API`, etc. I understand the name in both cases simply means C+ImGui, however I also personally feel like in order to reduce confusion, dear_bindings could change it to something unique, purely for differentiation reasons.

I've been personally confused because of this multiple types. When just seeing a file named `cimgui.cpp`, I have no clue what generator does it come from. When I first stumbled upon dear_bindings, this also made me think it's simply a modern reimplementation of https://github.com/cimgui/cimgui that aims to keep the output the same, which is not the case.

The new name doesn't have to be anything fancy, just something that allows for mental separation. Ideas:

- dcimgui (dear c imgui)
- dbcimgui (dear bindings c imgui)

The only downside I can think of is, it will be a breaking change for anyone currently using dear_bindings... But, we're only v0.11, anything reasonable goes?

**Comment by ocornut** [comment]
Personally I kinda of disagree. Both headers have mentions at the top of their file.
I suppose there are 2 questions: one for the (default) filenames and one for in-code prefixes and namespaces. 

Tangentially, at least one person told me they were reluctant to switch from cimgui to dear bindings because they prefer the `ig` prefix e.g. `igButton()` over `ImGui_Button()`. I personally don't fancy the `ig` prefix too much but it's nice that it is short, but I don't think it would be a bad property if most names were similar. 

> The only downside I can think of is, it will be a breaking change for anyone currently using dear_bindings...

I think it would be fine to rename file and symbols at this point, if that was deemed desirable.

**Comment by ShironekoBen** [comment]
The idea initially was to make it easy for people to switch, but I can definitely see that if you're in the situation where both at floating around the filenames don't make things easier.

`dcimgui.h` feels simpler than `dbcimgui.h` (even just typing the latter now I had to think about it - I'm not sure why by `dc` comes much more naturally to me than `dbc`). It's also a relatively benign change in the scheme of things because it's very easy to provide a filename override on the command line.

As for the symbol names.... hm.... personally I'm in the "`igButton()` feels kinda ugly, somehow?" camp, but I can't argue with the "there's less characters to type" aspect. Although in C++ land I'm pretty used to typing "ImGui::Button()", which is even longer - I'm not sure how prevalent it is for people to include the `ImGui` namespace since if you do that you end up with just `Button()` which is both confusing and very likely to clash with something.

That said, the idea of a `--custom-imgui-namespace-prefix` flag has some appeal - then if people want cimgui-style names they can get them with `--custom-imgui-namespace-prefix ig` (which would internally just effectively rename the `ImGui_` prefix to `ig` after flattening).

I'm going to leave this issue to sit for a week or to so that if anyone else has feedback they can chime in (and I'll ponder it in the meantime), but if nothing else comes up I think I'll try renaming the default output files and adding an optional namespace prefix modifier as described.

**Comment by zaafar** [comment]
> That said, the idea of a --custom-imgui-namespace-prefix flag has some appeal - then if people want cimgui-style names they can get them with --custom-imgui-namespace-prefix ig (which would internally just effectively rename the ImGui_ prefix to ig after flattening).

this is a good idea.

**Comment by zaafar** [comment]
> even just typing the latter now I had to think about it - I'm not sure why by dc comes much more naturally to me than dbc

prob cuz of DC comics :) anyway, changing filename is good change.

**Comment by ShironekoBen** [comment]
So I've gone ahead and implemented this - the default output name is now `dcimgui.h`, and there are now switches to control the prefixes... to quote the new readme file:

By default, Dear Bindings will use namespaces/class names to generate prefixes for names in the output - for example, `ImGui::Begin()` will become `ImGui_Begin()`.

However, you may want to customise these, especially if you are looking for compatibility with cimgui or similar. To achieve this, you can specify  `--custom-namespace-prefix` to replace `ImGui_` with something else - for example, `--custom-namespace-prefix ig` will result in `ImGui::Begin()` becoming `igBegin()` instead. For more detailed customisation, you can use `--replace-prefix`, which allows any arbitrary name prefix to be replaced - for example,  `--replace-prefix ImFont_=if` will result in `ImFont_FindGlyph()` becoming `ifFontGlyph()` (and all other `ImFont_` names following suit). You can specify as many `--replace-prefix` arguments as you like (although the results are undefined if you specify overlapping prefixes).

(for reference, `--custom-namespace-prefix Foo` is just a simplified syntax for `--replace-prefix ImGui_=Foo`)

**Comment by floooh** [comment]
Awesome stuff @ShironekoBen :)

Slight related, for language bindings it might also be useful to have no prefix at all (don't know if this is currently possible), for example look at this Zig code which uses Zig's 'translate-c' feature on the traditional cimgui API. It would be nice if the `ig` prefix could be dropped, so that it looks like `ig.SetNextWindowPos()` (to be fully 'Zig idiomatic' it should be `ig.setNextWindowPos()`, but that's probably too much to ask ;)

```zig
    ig.igSetNextWindowPos(.{ .x = 10, .y = 10 }, ig.ImGuiCond_Once, .{ .x = 0, .y = 0 });
    ig.igSetNextWindowSize(.{ .x = 400, .y = 100 }, ig.ImGuiCond_Once);
    _ = ig.igBegin("Hello Dear ImGui!", 0, ig.ImGuiWindowFlags_None);
    _ = ig.igColorEdit3("Background", &state.pass_action.colors[0].clear_value.r, ig.ImGuiColorEditFlags_None);
    ig.igEnd();
```

**Comment by ShironekoBen** [comment]
Hmm, an interesting idea. I can't say I've tested it extensively, but `--replace-prefix ImGui_=` seems to have the desired effect there... although given that in virtually all cases these symbols are going to get exported as C symbols from a library at some point, I'm not sure how much chaos having likely-to-collide things like `Begin` defined is going to be?

It feels like for most use-cases doing that sort of renaming in the higher-level language layer is likely to be more useful, but if anyone does want it then the option is there!

**Comment by floooh** [comment]
Btw, I just discovered that building the C bindings without prefix produces a collision with some Win32 function names (GetWindowPos, SetCursorPos, GetCursorPos) - so probably not a good idea to go without a prefix in the C bindings :)

I think it's better to deal with this problem in language-specific bindings which then call down into the C bindings (e.g. if I want a Zig bindings naming convention like `ig.setNextWindowPos(...)`, then this should be handled by a separate Zig module (which can also be generated from the JSON metadata).
