### ISSUE TITLE
Generated C header requires to be used in C11 mode?

### ISSUE THREAD

**Issue by floooh** [dearimgui/dear_bindings#82]
Hiho, I'm in the process of switching from cimgui to dear_bindings (the 'new' API with the split between regular and Ex function is nice!).

One thing I noticed though is that compilation in C99 mode gives warnings about duplicate symbols in the generated C header (for instance `ImVec2` and `ImVec2_t` is defined here: https://github.com/floooh/dcimgui/blob/116069a2faa188e4ace87003cc184119ff7ee1cd/src/cimgui.h#L316-L320 and here: https://github.com/floooh/dcimgui/blob/116069a2faa188e4ace87003cc184119ff7ee1cd/src/cimgui.h#L154.

In C11 this is completely fine, but not in earlier versions.

Is this intended? For me it's not a big deal to build in C11, but if it is easily avoidable it might make sense to emit those types only once?

**Comment by ShironekoBen** [comment]
Ah, indeed, you're absolutely right there. I'd kinda blanked out the fact that technically that's both forward-declaring the struct and then typedefing it as well, and whilst the former is a valid thing to do the latter means that the "real" definition repeats the typedef which isn't technically allowed in C99.

I've put in a quick fix that resolves the issue for `imgui.h` by omitting the typedef from the second declaration. This doesn't sadly fix it in all cases, as if you use `imgui_internal.h` then it gets upset about the fact that some things are typedef'd in the (included) `imgui.h` and then again in `imgui_internal.h`. That's probably fixable but will probably have to wait for another day as I'm a little short on time to dive into a more fully-featured "remove all redundant forward declarations" feature right this second, I'm afraid!

Hope that helps out a bit, at least, and give me a shout if the `imgui_internal.h` thing is a problem for your use-case and I'll try to get onto it sooner rather than later!

Thanks for the report!
